coffee_dw:
  target: postgres
  outputs:
    postgres:
      type: postgres
      host: host.docker.internal
      user: postgres
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: coffee_dw
      schema: dbo
      threads: 8