global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'kafka-connect'
    static_configs:
      - targets: ['connect:9300']

  - job_name: 'kafka-broker'
    static_configs:
      - targets: ['kafka-1:9300', 'kafka-2:9300', 'kafka-3:9300']